FROM       centos:7.2.1511
MAINTAINER layfolk
ENV        LANG              en_US.utf8
RUN        rm -f /etc/yum.repos.d/* && cat /etc/redhat-release | awk '{print $4}' > /etc/yum/vars/full_releasever
ADD        centos-7.repo epel-7.repo /etc/yum.repos.d/
RUN        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && yum install -y rpm-build gcc zlib-devel pam-devel openssl-devel wget libXt-devel imake gtk2-devel krb5-devel make && rm -rf /var/cache/yum
